### smasher_state.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

@abstract
class_name SmasherState
extends RefCounted

var smasher: Smasher
var fsm: SmasherFSM:
	get: return _fsm_ref.get_ref() as SmasherFSM

var _fsm_ref: WeakRef


func _init(smasher_: Smasher, fsm_: SmasherFSM) -> void:
	smasher = smasher_
	_fsm_ref = weakref(fsm_)

@warning_ignore_start("unused_parameter")
func on_enter() -> void: pass
func on_exit() -> void: pass
func on_input(event: InputEvent) -> void: pass
func on_process(delta: float) -> void: pass
func on_physics_process(delta: float) -> void: pass
@warning_ignore_restore("unused_parameter")

### END GENERATED CONTENT ###
