### smasher_state_exploding.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SmasherStateExploding
extends SmasherState

func _to_string() -> String:
	return "exploding"

### END GENERATED CONTENT ###
