### smasher_state_smashing.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SmasherStateSmashing
extends SmasherState

func _to_string() -> String:
	return "smashing"

### END GENERATED CONTENT ###
