### smasher_fsm.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SmasherFSM
extends RefCounted

signal transitioned(from_state: SmasherState, to_state: SmasherState)

var idle_state: SmasherStateIdle
var patrolling_state: SmasherStatePatrolling
var smashing_state: SmasherStateSmashing
var exploding_state: SmasherStateExploding

var current_state: SmasherState
var transition_id: int = 0


func _init(smasher_: Smasher) -> void:
	idle_state = SmasherStateIdle.new(smasher_, self)
	patrolling_state = SmasherStatePatrolling.new(smasher_, self)
	smashing_state = SmasherStateSmashing.new(smasher_, self)
	exploding_state = SmasherStateExploding.new(smasher_, self)
	_enter_state(idle_state)


func _to_string() -> String:
	return "SmasherFSM{state=%s}" % str(current_state)


func input(event: InputEvent) -> void:
	current_state.on_input(event)


func process(delta: float) -> void:
	current_state.on_process(delta)


func physics_process(delta: float) -> void:
	current_state.on_physics_process(delta)


func transition_to(new_state: SmasherState) -> void:
	if new_state == current_state:
		return
	var previous_state: SmasherState = current_state
	_exit_state(current_state)
	transition_id += 1
	_enter_state(new_state)
	transitioned.emit(previous_state, new_state)


func transition_to_idle_state() -> void:
	transition_to(idle_state)


func transition_to_patrolling_state() -> void:
	transition_to(patrolling_state)


func transition_to_smashing_state() -> void:
	transition_to(smashing_state)


func transition_to_exploding_state() -> void:
	transition_to(exploding_state)


func _enter_state(state: SmasherState) -> void:
	current_state = state
	state.on_enter()


func _exit_state(state: SmasherState) -> void:
	state.on_exit()

### END GENERATED CONTENT ###
