### smasher_state_patrolling.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SmasherStatePatrolling
extends SmasherState

func _to_string() -> String:
	return "patrolling"

### END GENERATED CONTENT ###
