### smasher_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SmasherStateIdle
extends SmasherState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###


func on_enter() -> void:
	pass


func on_exit() -> void:
	pass
