### scene_manager.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###
extends Node


class Scene:
	var _scene_name: StringName
	var _instance_factory: Callable
	var _instance: Node

	func _init(scene_name: StringName, instance_factory: Callable) -> void:
		_scene_name = scene_name
		_instance_factory = instance_factory

	func _to_string() -> String:
		return String(_scene_name)

	func instance() -> Node:
		if !_instance:
			_instance = _instance_factory.call()
		return _instance

	func free_instance() -> void:
		assert(is_instance_valid(_instance))
		_instance.queue_free()
		_instance = null

	func enter() -> void:
		assert(is_instance_valid(_instance))
		if _instance.has_method("on_enter"):
			@warning_ignore("redundant_await")
			await _instance.on_enter()

	func exit() -> void:
		assert(is_instance_valid(_instance))
		if _instance.has_method("on_exit"):
			@warning_ignore("redundant_await")
			await _instance.on_exit()

	func focus() -> void:
		assert(is_instance_valid(_instance))
		if _instance.has_method("on_focus"):
			@warning_ignore("redundant_await")
			await _instance.on_focus()

	func blur() -> void:
		assert(is_instance_valid(_instance))
		if _instance.has_method("on_blur"):
			@warning_ignore("redundant_await")
			await _instance.on_blur()


signal transitioned(from_scene: Scene, to_scene: Scene)

var _container: Node
var _initialized: bool = false
var _scene_stack: Array[Scene]

var current_scene: Scene:
	get: return _scene_stack[-1] if not _scene_stack.is_empty() else null

var title_scene: Scene
var game_scene: Scene
var game_over_scene: Scene
var game_won_scene: Scene
var paused_scene: Scene
var options_scene: Scene


func init(container: Node) -> void:
	assert(!_initialized, "Scene manager already initialized")
	_container = container
	title_scene = Scene.new(&"title", default_instance_factory("res://ui/title/title.tscn"))
	game_scene = Scene.new(&"game", default_instance_factory("res://game/game.tscn"))
	game_over_scene = Scene.new(&"game_over", default_instance_factory("res://ui/game_over/game_over.tscn"))
	game_won_scene = Scene.new(&"game_won", default_instance_factory("res://ui/game_won/game_won.tscn"))
	paused_scene = Scene.new(&"paused", default_instance_factory("res://ui/pause/pause.tscn"))
	options_scene = Scene.new(&"options", default_instance_factory("res://ui/options/options.tscn"))
	_initialized = true
	push_scene(title_scene)


static func default_instance_factory(path: String) -> Callable:
	return Callable(func(): return load(path).instantiate())


func push_scene(scene: Scene) -> void:
	assert(_initialized, "Scene manager not initialized — call init() first")
	assert(scene not in _scene_stack, "Scene '%s' already shown" % scene)

	var previous_scene: Scene = current_scene
	if !_scene_stack.is_empty():
		_scene_stack[-1].blur()

	var instance: Node = scene.instance()
	_container.add_child(instance)
	_scene_stack.push_back(scene)
	scene.enter()
	_scene_stack[-1].focus()
	transitioned.emit(previous_scene, scene)


func pop_scene() -> void:
	assert(_initialized, "Scene manager not initialized — call init() first")
	assert(_scene_stack.size() >= 1)
	var popped_scene: Scene = _scene_stack.pop_back()
	popped_scene.blur()

	popped_scene.exit()
	popped_scene.free_instance()

	if !_scene_stack.is_empty():
		_scene_stack[-1].focus()
	transitioned.emit(popped_scene, current_scene)


func replace_scene(scene: Scene) -> void:
	while !_scene_stack.is_empty():
		pop_scene()
	push_scene(scene)


func push_title_scene() -> void:
	push_scene(title_scene)


func replace_with_title_scene() -> void:
	replace_scene(title_scene)


func push_game_scene() -> void:
	push_scene(game_scene)


func replace_with_game_scene() -> void:
	replace_scene(game_scene)


func push_game_over_scene() -> void:
	push_scene(game_over_scene)


func replace_with_game_over_scene() -> void:
	replace_scene(game_over_scene)


func push_game_won_scene(num_deaths: int, time_taken: int) -> void:
	var scene_instance: Node = game_won_scene.instance()
	scene_instance.num_deaths = num_deaths
	scene_instance.time_taken = time_taken
	push_scene(game_won_scene)


func replace_with_game_won_scene(num_deaths: int, time_taken: int) -> void:
	var scene_instance: Node = game_won_scene.instance()
	scene_instance.num_deaths = num_deaths
	scene_instance.time_taken = time_taken
	replace_scene(game_won_scene)


func push_paused_scene() -> void:
	push_scene(paused_scene)


func replace_with_paused_scene() -> void:
	replace_scene(paused_scene)


func push_options_scene() -> void:
	push_scene(options_scene)


func replace_with_options_scene() -> void:
	replace_scene(options_scene)

### END GENERATED CONTENT ###
