### player_state.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

@abstract
class_name PlayerState
extends RefCounted

var player: Player
var fsm: PlayerFSM:
	get: return _fsm_ref.get_ref() as PlayerFSM

var _fsm_ref: WeakRef


func _init(player_: Player, fsm_: PlayerFSM) -> void:
	player = player_
	_fsm_ref = weakref(fsm_)

@warning_ignore_start("unused_parameter")
func on_enter() -> void: pass
func on_exit() -> void: pass
func on_input(event: InputEvent) -> void: pass
func on_process(delta: float) -> void: pass
func on_physics_process(delta: float) -> void: pass
@warning_ignore_restore("unused_parameter")

### END GENERATED CONTENT ###

func play_hit_flash() -> void:
	var palette_shader: PaletteShader = PaletteShader.get_instance()
	var static_fx: StaticFX = StaticFX.get_instance()
	palette_shader.brightness = 0.6
	static_fx.coverage = lerpf(0, 0.4, 1 - (player.health / float(Player.MAX_HEALTH)))
	static_fx.seed_a += 1
	player.sprite.play("hit")
	await player.sprite.animation_finished
	static_fx.coverage = 0
	palette_shader.brightness = 0


func play_grounded_anim(settle_anim: String) -> void:
	# If we just landed from a fall, play the crouch first, then settle into the
	# given animation; otherwise play it straight away. The transition guard keeps
	# the deferred settle from stomping a state we left during the crouch.
	if player.landed:
		player.landed = false
		player.sprite.play("crouch")
		var trans_id: int = fsm.transition_id
		await Util.timer(Player.LAND_CROUCH_TIME)
		if trans_id != fsm.transition_id:
			return
	player.sprite.play(settle_anim)


func is_idle() -> bool:
	var on_floor: bool = player.is_on_floor()
	var not_moving: bool = is_zero_approx(player.current_speed) and player.velocity.y >= 0
	return on_floor and not_moving


func is_stretching() -> bool:
	return Input.is_action_pressed("stretch")


func is_falling() -> bool:
	return not player.is_on_floor() and player.velocity.y >= 0
 

func is_moving() -> bool:
	return player.input.moving and player.is_on_floor()


func is_dropping() -> bool:
	var on_floor: bool = player.is_on_floor()
	var input_pressed: bool = player.input.down_strength > 0.7 and player.input.jump_pressed
	return on_floor and input_pressed


func is_dropping_from_hang() -> bool:
	return player.input.jump_just_pressed


func is_intersecting_rail() -> bool:
	return player.attach_ray_cast.is_colliding()


func intersecting_rail() -> Rail:
	if not is_intersecting_rail():
		return null
	var collider: Object = player.attach_ray_cast.get_collider()
	return collider as Rail


func is_jumping() -> bool:
	var on_floor: bool = player.is_on_floor()
	var normal_jump: bool = player.input.jump_just_pressed and on_floor
	var coyote_jump: bool = player.input.jump_just_pressed and player.coyote_time_remaining > 0
	var buffered_jump: bool = player.jump_buffer_time_remaining > 0 and on_floor
	return normal_jump or coyote_jump or buffered_jump


func apply_gravity(delta: float) -> void:
	if not player.is_on_floor():
		player.velocity += player.get_gravity() * delta


func drop() -> void:
	player.velocity = Vector2.ZERO
	player.floor_snap_length = 0
	player.global_position.y += 2
	player.was_dropped = true
	fsm.transition_to(fsm.falling_state)


func apply_movement(delta: float) -> void:
	apply_gravity(delta)

	var direction: float = player.input.move_direction
	if not is_zero_approx(direction):
		player.sprite.flip_h = signf(direction) == 1

	var same_direction: bool = signf(direction) == signf(player.velocity.x)
	var adjusted_accel: float = Player.ACCEL_SPEED if same_direction else Player.DECEL_SPEED
	var adjusted_speed: float = Player.GROUND_SPEED if player.is_on_floor() else Player.AIR_SPEED
	if not player.is_on_floor() and direction and same_direction:
		adjusted_speed = max(adjusted_speed, abs(player.velocity.x))

	if direction:
		player.current_speed = move_toward(player.current_speed, direction * adjusted_speed, adjusted_accel * delta)
		player.direction = direction
	else:
		player.current_speed = move_toward(player.current_speed, 0, Player.DECEL_SPEED * delta)

	player.velocity.x = player.current_speed
	player.move_and_slide()


func apply_stretch(delta: float) -> void:
	if is_stretching():
		player.height = move_toward(player.height, Player.MAX_HEIGHT, Player.STRETCH_SPEED * delta)
	else:
		player.height = move_toward(player.height, Player.MIN_HEIGHT, Player.STRETCH_SPEED * delta)
