### player_state_hit.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateHit
extends PlayerState

func _to_string() -> String:
	return "hit"

### END GENERATED CONTENT ###

func on_enter() -> void:
	pass
	await player.sprite.animation_finished
	fsm.transition_to_idle_state()
