### player_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateIdle
extends PlayerState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###


func on_enter() -> void:
	player.sprite.play("idle")


func on_physics_process(delta: float) -> void:
	apply_stretch(delta)
	apply_movement(delta)

	if is_intersecting_rail():
		fsm.transition_to_hanging_state()
		return

	if is_moving():
		fsm.transition_to_moving_state()
		return

	if is_dropping():
		drop()
		return

	if is_jumping():
		fsm.transition_to_jumping_state()
		return
