### player_state_dying.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateDying
extends PlayerState

func _to_string() -> String:
	return "dying"

### END GENERATED CONTENT ###

func on_enter() -> void:
	SignalBus.player_dying.emit()
	player.hit_sfx.play()
	player.hit_box_collider.set_deferred("disabled", true)
	await play_hit_flash()
	player.death_sfx.play()
	player.sprite.play("dying")
	await player.sprite.animation_finished
	player.hide()


	var static_fx: StaticFX = StaticFX.get_instance()
	var palette_shader: PaletteShader = PaletteShader.get_instance()
	var tween: Tween = player.create_tween()
	tween.set_parallel(true)
	tween.tween_property(static_fx, "coverage", 1, 1)
	tween.tween_property(static_fx, "column_strength", 0, 1)
	tween.tween_property(palette_shader, "brightness", 1, 1)
	await tween.finished
	static_fx.reset()

	var game: Game = Game.get_instance()
	if game.lives == 0:
		SceneManager.replace_with_game_over_scene()
		return

	SignalBus.player_died.emit()
	await Util.timer(1)
	game.lives -= 1
	await Util.timer(1)
	SignalBus.player_restarted_level.emit()
