### player_state_debug.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateDebug
extends PlayerState

func _to_string() -> String:
	return "debug"

### END GENERATED CONTENT ###

const DEBUG_SPEED: float = 300.0

var _saved_collision_layer: int
var _saved_collision_mask: int
var _saved_hit_box_monitoring: bool
var _saved_hit_box_monitorable: bool


func on_enter() -> void:
	player.velocity = Vector2.ZERO
	player.sprite.play("idle")

	_saved_collision_layer = player.collision_layer
	_saved_collision_mask = player.collision_mask
	_saved_hit_box_monitoring = player.hit_box.monitoring
	_saved_hit_box_monitorable = player.hit_box.monitorable

	player.collision_layer = 0
	player.collision_mask = 0
	player.hit_box.monitoring = false
	player.hit_box.monitorable = false


func on_exit() -> void:
	player.velocity = Vector2.ZERO
	player.collision_layer = _saved_collision_layer
	player.collision_mask = _saved_collision_mask
	player.hit_box.set_deferred("monitoring", _saved_hit_box_monitoring)
	player.hit_box.set_deferred("monitorable", _saved_hit_box_monitorable)


func on_physics_process(delta: float) -> void:
	player.global_position += player.input.move * DEBUG_SPEED * delta
