### player_state_dying.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateDying
extends PlayerState

func _to_string() -> String:
	return "dying"

### END GENERATED CONTENT ###
