### player_state_debug.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateDebug
extends PlayerState

func _to_string() -> String:
	return "debug"

### END GENERATED CONTENT ###

const DEBUG_SPEED: float = 300.0

var _saved_collision_layer: int
var _saved_collision_mask: int


func on_enter() -> void:
	player.velocity = Vector2.ZERO
	player.sprite.play("idle")

	_saved_collision_layer = player.collision_layer
	_saved_collision_mask = player.collision_mask

	player.collision_layer = 0
	player.collision_mask = 0
	player.hit_box.monitoring = false
	player.hit_box.monitorable = false
	# RayCast2D queries match on collision_layer and ignore monitoring/monitorable,
	# so the hit box must be taken off its layer to hide it from raycasts (e.g. the roller).
	player.hit_box.collision_layer = 0


func on_exit() -> void:
	player.velocity = Vector2.ZERO
	player.collision_layer = _saved_collision_layer
	player.collision_mask = _saved_collision_mask
	# Defer hit box restoration to the player's standalone toggle so the two debug modes
	# stay consistent (e.g. if invincibility was toggled on while in debug move).
	player.apply_hitbox_disabled()


func on_physics_process(delta: float) -> void:
	player.global_position += player.input.move * DEBUG_SPEED * delta
