### player_fsm.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerFSM
extends RefCounted

signal transitioned(from_state: PlayerState, to_state: PlayerState)

var idle_state: PlayerStateIdle
var hit_state: PlayerStateHit
var moving_state: PlayerStateMoving
var jumping_state: PlayerStateJumping
var falling_state: PlayerStateFalling
var hanging_state: PlayerStateHanging
var disabled_state: PlayerStateDisabled
var dying_state: PlayerStateDying
var dead_state: PlayerStateDead
var debug_state: PlayerStateDebug
var spawning_state: PlayerStateSpawning

var current_state: PlayerState
var transition_id: int = 0


func _init(player_: Player) -> void:
	idle_state = PlayerStateIdle.new(player_, self)
	hit_state = PlayerStateHit.new(player_, self)
	moving_state = PlayerStateMoving.new(player_, self)
	jumping_state = PlayerStateJumping.new(player_, self)
	falling_state = PlayerStateFalling.new(player_, self)
	hanging_state = PlayerStateHanging.new(player_, self)
	disabled_state = PlayerStateDisabled.new(player_, self)
	dying_state = PlayerStateDying.new(player_, self)
	dead_state = PlayerStateDead.new(player_, self)
	debug_state = PlayerStateDebug.new(player_, self)
	spawning_state = PlayerStateSpawning.new(player_, self)
	_enter_state(idle_state)


func _to_string() -> String:
	return "PlayerFSM{state=%s}" % str(current_state)


func input(event: InputEvent) -> void:
	current_state.on_input(event)


func process(delta: float) -> void:
	current_state.on_process(delta)


func physics_process(delta: float) -> void:
	current_state.on_physics_process(delta)


func transition_to(new_state: PlayerState) -> void:
	if new_state == current_state:
		return
	var previous_state: PlayerState = current_state
	_exit_state(current_state)
	transition_id += 1
	_enter_state(new_state)
	transitioned.emit(previous_state, new_state)


func transition_to_idle_state() -> void:
	transition_to(idle_state)


func transition_to_hit_state() -> void:
	transition_to(hit_state)


func transition_to_moving_state() -> void:
	transition_to(moving_state)


func transition_to_jumping_state() -> void:
	transition_to(jumping_state)


func transition_to_falling_state() -> void:
	transition_to(falling_state)


func transition_to_hanging_state() -> void:
	transition_to(hanging_state)


func transition_to_disabled_state() -> void:
	transition_to(disabled_state)


func transition_to_dying_state() -> void:
	transition_to(dying_state)


func transition_to_dead_state() -> void:
	transition_to(dead_state)


func transition_to_debug_state() -> void:
	transition_to(debug_state)


func transition_to_spawning_state() -> void:
	transition_to(spawning_state)


func _enter_state(state: PlayerState) -> void:
	current_state = state
	state.on_enter()


func _exit_state(state: PlayerState) -> void:
	state.on_exit()

### END GENERATED CONTENT ###
