### player_state_dead.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateDead
extends PlayerState

func _to_string() -> String:
	return "dead"

### END GENERATED CONTENT ###
