### player_state_disabled.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateDisabled
extends PlayerState

func _to_string() -> String:
	return "disabled"

### END GENERATED CONTENT ###
