### player_state_moving.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateMoving
extends PlayerState

func _to_string() -> String:
	return "moving"

### END GENERATED CONTENT ###

 
func on_physics_process(delta: float) -> void:
	apply_movement(delta)
	apply_stretch(delta)

	player.was_on_floor = true

	if is_intersecting_rail():
		fsm.transition_to_hanging_state()
		return

	if is_idle():
		fsm.transition_to_idle_state()
		return

	if is_jumping():
		fsm.transition_to_jumping_state()
		return

	if is_falling():
		fsm.transition_to_falling_state()
		return
