### player_state_spawning.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateSpawning
extends PlayerState

func _to_string() -> String:
	return "spawning"

### END GENERATED CONTENT ###

func on_enter() -> void:
	player.show()
	player.play_sfx(player.spawn_sfx)
	player.sprite.play("spawning")
	await player.sprite.animation_finished
	fsm.transition_to_idle_state()
