### player_state_falling.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateFalling
extends PlayerState

func _to_string() -> String:
	return "falling"

### END GENERATED CONTENT ###

func on_enter() -> void:
	if player.was_on_floor and not player.was_dropped:
		player.coyote_time_remaining = Player.COYOTE_TIME
	player.was_dropped = false


func on_exit() -> void:
	player.floor_snap_length = Player.DEFAULT_SNAP_LENGTH


func on_physics_process(delta: float) -> void:
	apply_stretch(delta)
	apply_movement(delta)

	player.coyote_time_remaining = max(0, player.coyote_time_remaining - delta)
	player.jump_buffer_time_remaining = max(0, player.jump_buffer_time_remaining - delta)

	# Buffer a jump press so it can fire on landing, and consume coyote time
	# while still airborne. Must run in physics where input is freshly updated.
	if player.input.jump_just_pressed:
		player.jump_buffer_time_remaining = Player.JUMP_BUFFER_TIME

	if player.velocity.y > Player.TERMINAL_VELOCITY:
		player.velocity.y = Player.TERMINAL_VELOCITY

	if is_jumping():
		fsm.transition_to(fsm.jumping_state)
		return

	if is_intersecting_rail():
		fsm.transition_to_hanging_state()
		return

	if is_idle():
		fsm.transition_to(fsm.idle_state)
		return

	if is_moving():
		fsm.transition_to(fsm.moving_state)
		return
