### player_state_hanging.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateHanging
extends PlayerState

func _to_string() -> String:
	return "hanging"

### END GENERATED CONTENT ###

var rotation_tween: Tween
var recoil_direction: float
var has_recoiled: bool
var prev_direction: float
var is_attached: bool
var move_anim_reversed: bool
var spark_burst_remaining: float

func on_enter() -> void:
	player.wheel_collider.disabled = false
	player.velocity = Vector2.ZERO
	player.attached_rail = intersecting_rail()
	Log.info(self, on_enter, "Attaching to rail %s" % player.attached_rail)

	player.attach_to_rail_sfx.play()
	player.sprite.play("hanging")

	# Burst both sparks briefly on attach.
	player.spark_left.emitting = true
	player.spark_right.emitting = true
	spark_burst_remaining = Player.RAIL_SPARK_BURST_TIME

	var collision_point: Vector2 = player.attach_ray_cast.get_collision_point()
	var local_point: Vector2 = player.attached_rail.path.to_local(collision_point)
	var progress: float = player.attached_rail.path.curve.get_closest_offset(local_point)

	player.rail_follower.reparent(player.attached_rail.path)
	player.rail_follower.progress = progress
	player.global_position = player.rail_follower.global_position

	player.wheel_sprite.show()
	player.wheel_sprite.speed_scale = 1
	player.wheel_sprite.play("appear")

	await player.wheel_sprite.animation_finished
	player.wheel_sprite.play("forward")
	has_recoiled = false
	prev_direction = 0.0
	is_attached = true


func on_exit() -> void:
	is_attached = false
	player.spark_left.emitting = false
	player.spark_right.emitting = false
	player.detach_from_rail_sfx.play()
	player.wheel_collider.set_deferred("disabled", true)
	player.attach_ray_cast.add_exception(player.attached_rail)
	player.attached_rail = null
	player.rail_follower.reparent(player)
	player.rail_follower.global_position = player.global_position
	player.wheel_sprite.speed_scale = 1
	player.wheel_sprite.play_backwards("appear")

	await player.wheel_sprite.animation_finished
	player.wheel_sprite.hide()

	if rotation_tween:
		rotation_tween.kill()
	rotation_tween = player.create_tween()
	rotation_tween.tween_property(player.sprite_group, "rotation_degrees", 0, 0.2)
	
	await Util.timer(Player.RAIL_EXCLUSION_TIME)
	player.attach_ray_cast.clear_exceptions()


func on_physics_process(delta: float) -> void:
	apply_stretch(delta)
	apply_rail_movement(delta)
	# apply_rail_movement may drop off the rail (transitioning out and turning sparks
	# off in on_exit); guard on is_attached so we don't re-light them this same frame.
	if is_attached:
		update_sparks(delta)
		var speed_scale: float = 2 * player.current_speed / Player.RAIL_SPEED
		if player.wheel_sprite.animation == "forward":
			player.wheel_sprite.speed_scale = speed_scale


func update_sparks(delta: float) -> void:
	# Keep both sparks lit during the attach burst window.
	if spark_burst_remaining > 0.0:
		spark_burst_remaining -= delta
		return

	if absf(player.current_speed) < Player.RAIL_SPARK_MIN_SPEED:
		player.spark_left.emitting = false
		player.spark_right.emitting = false
		return

	# Spark on the side opposite the travel direction (trailing the wheel).
	var moving_right: bool = player.current_speed > 0.0
	player.spark_left.emitting = moving_right
	player.spark_right.emitting = not moving_right


func apply_rail_movement(delta: float) -> void:
	var direction: float = player.input.move_direction
	var same_direction: bool = signf(direction) == signf(player.velocity.x)

	var adjusted_accel: float = Player.RAIL_ACCEL_SPEED if same_direction else Player.RAIL_DECEL_SPEED
	var adjusted_speed: float = Player.RAIL_SPEED
	var rail_len: float = player.attached_rail.path.curve.get_baked_length()

	if direction:
		player.sprite.flip_h = signf(direction) == 1
		player.current_speed = move_toward(player.current_speed, direction * adjusted_speed, adjusted_accel * delta)
		player.direction = direction
	else:
		player.current_speed = move_toward(player.current_speed, 0, Player.RAIL_DECEL_SPEED * delta)


	var want_reverse: bool = is_zero_approx(direction)
	if want_reverse:
		# Key released. Run the move clip backwards and only settle into "hanging"
		# once that reverse has actually finished playing (not when speed hits 0).
		if player.sprite.animation == "hanging_move":
			if not move_anim_reversed:
				move_anim_reversed = true
				player.sprite.play_backwards("hanging_move")
			elif not player.sprite.is_playing():
				player.sprite.play("hanging")
		elif player.sprite.animation != "hanging":
			player.sprite.play("hanging")
	else:
		# Key held.
		if absf(player.current_speed) > 0:
			if player.sprite.animation != "hanging_move" or move_anim_reversed:
				move_anim_reversed = false
				player.sprite.play("hanging_move")
		elif player.sprite.animation != "hanging":
			player.sprite.play("hanging")

	var rail_motion: float = player.current_speed * delta
	var rotation_tween_active: bool = rotation_tween != null and rotation_tween.is_running()

	if rotation_tween_active and direction != 0.0 and signf(direction) != recoil_direction:
		rotation_tween.kill()
		rotation_tween_active = false

	if not rotation_tween_active and not has_recoiled:
		if is_zero_approx(direction) and not is_zero_approx(prev_direction):
			# Just stopped — recoil back upright, scaled by how far we were leaning.
			var strength: float = absf(player.sprite_group.rotation_degrees) / 6.0
			play_recoil(signf(prev_direction), strength)
			rotation_tween_active = true
		elif not is_zero_approx(direction):
			# Lean into the movement.
			var target_tilt: float = 6.0 * signf(direction)
			player.sprite_group.rotation_degrees = move_toward(
				player.sprite_group.rotation_degrees,
				target_tilt,
				Player.RAIL_TILT_ACCEL_SPEED * delta
			)

	prev_direction = direction

	# Lock the follower to the player's point on the rail, then step it forward by rail_motion.
	# Moving by the follower's own step keeps travel tied to the sign of current_speed, so an
	# obstacle that shoves the body along the rail can't reverse our direction and re-pin us.
	var foot_local: Vector2 = player.attached_rail.path.to_local(player.global_position)
	player.rail_follower.progress = player.attached_rail.path.curve.get_closest_offset(foot_local)
	var foot_pos: Vector2 = player.rail_follower.global_position
	player.rail_follower.progress += rail_motion

	# The rail step, plus only the perpendicular part of the pull back onto the rail (drop the
	# tangential part so re-centering the body never fights the step).
	var step: Vector2 = player.rail_follower.global_position - foot_pos
	var to_rail: Vector2 = foot_pos - player.global_position
	var tangent: Vector2 = step.normalized()
	var motion: Vector2 = step + to_rail - tangent * to_rail.dot(tangent)
	player.velocity = motion / delta

	var collision: KinematicCollision2D = player.move_and_collide(motion)
	# Only a block if we're driving into the surface. Moving away from a wall we're still
	# touching also reports a collision, so checking the normal keeps the stop reversible.
	var hit_wall: bool = collision != null and collision.get_normal().dot(motion) < 0.0
	if hit_wall:
		player.move_and_collide(collision.get_remainder())
		var local_point: Vector2 = player.attached_rail.path.to_local(player.global_position)
		var progress: float = player.attached_rail.path.curve.get_closest_offset(local_point)
		player.rail_follower.progress = progress

	# Drop off if we ran off an open end. Progress is clamped (loop = false), so these are exact.
	var at_left_end: bool = player.rail_follower.progress <= 0.0
	var at_right_end: bool = player.rail_follower.progress >= rail_len
	if at_left_end and player.attached_rail.open_on_left:
		drop_off_rail(true)
		return
	elif at_right_end and player.attached_rail.open_on_right:
		drop_off_rail(false)
		return

	# Blocked by a wall or a closed rail end: stop and recoil once per contact.
	var blocked: bool = hit_wall or at_left_end or at_right_end
	if blocked:
		player.current_speed = 0
		if not has_recoiled and not (rotation_tween != null and rotation_tween.is_running()):
			has_recoiled = true
			var recoil_sign: float = signf(rail_motion) if hit_wall else (-1.0 if at_left_end else 1.0)
			play_recoil(recoil_sign)
	else:
		# Free to move — allow the recoil to play again on the next fresh contact.
		has_recoiled = false

	if is_dropping_from_hang():
		drop()
		return


func play_recoil(dir_sign: float, strength: float = 1.0) -> void:
	if rotation_tween:
		rotation_tween.kill()
	recoil_direction = dir_sign
	rotation_tween = player.create_tween()
	rotation_tween.tween_property(player.sprite_group, "rotation_degrees", -6 * dir_sign * strength, 0.2)
	rotation_tween.tween_property(player.sprite_group, "rotation_degrees", 4 * dir_sign * strength, 0.2)
	rotation_tween.tween_property(player.sprite_group, "rotation_degrees", 0, 0.2)


func drop_off_rail(left_side: bool) -> void:
	player.velocity.x = player.current_speed
	player.floor_snap_length = 0
	var dir_sign: float = -1 if left_side else 1
	player.global_position.x += dir_sign * 2
	player.was_dropped = true
	fsm.transition_to(fsm.falling_state)
