### player_state_jumping.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name PlayerStateJumping
extends PlayerState

func _to_string() -> String:
	return "jumping"

### END GENERATED CONTENT ###

var jump_active: bool
var jump_time_remaining: float


func on_enter() -> void:
	player.coyote_time_remaining = 0
	player.jump_buffer_time_remaining = 0
	player.was_on_floor = false

	jump_time_remaining = Player.VARIABLE_JUMP_TIME
	jump_active = true
	player.velocity.y = Player.JUMP_HEIGHT
	player.sprite.play("jumping")
	player.play_sfx(player.jump_sfx)


func on_exit() -> void:
	jump_active = false


func on_physics_process(delta: float) -> void:
	# Variable height jumping — must run before move_and_slide
	if jump_active:
		if player.input.jump_pressed:
			jump_time_remaining = max(0, jump_time_remaining - delta)
			if is_zero_approx(jump_time_remaining):
				jump_active = false
			else:
				player.velocity.y = Player.JUMP_HEIGHT
		else:
			jump_active = false

	apply_stretch(delta)
	apply_movement(delta)

	if is_intersecting_rail():
		fsm.transition_to_hanging_state()
		return

	if player.is_on_ceiling():
		player.velocity.y = 0
		fsm.transition_to(fsm.falling_state)
		return

	if is_falling():
		fsm.transition_to(fsm.falling_state)
		return

	if is_idle():
		fsm.transition_to(fsm.idle_state)
		return
