### spinner_fsm.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SpinnerFSM
extends RefCounted

signal transitioned(from_state: SpinnerState, to_state: SpinnerState)

var idle_state: SpinnerStateIdle
var spinning_state: SpinnerStateSpinning
var exploding_state: SpinnerStateExploding

var current_state: SpinnerState
var transition_id: int = 0


func _init(spinner_: Spinner) -> void:
	idle_state = SpinnerStateIdle.new(spinner_, self)
	spinning_state = SpinnerStateSpinning.new(spinner_, self)
	exploding_state = SpinnerStateExploding.new(spinner_, self)
	_enter_state(idle_state)


func _to_string() -> String:
	return "SpinnerFSM{state=%s}" % str(current_state)


func input(event: InputEvent) -> void:
	current_state.on_input(event)


func process(delta: float) -> void:
	current_state.on_process(delta)


func physics_process(delta: float) -> void:
	current_state.on_physics_process(delta)


func transition_to(new_state: SpinnerState) -> void:
	if new_state == current_state:
		return
	var previous_state: SpinnerState = current_state
	_exit_state(current_state)
	transition_id += 1
	_enter_state(new_state)
	transitioned.emit(previous_state, new_state)


func transition_to_idle_state() -> void:
	transition_to(idle_state)


func transition_to_spinning_state(target_node: Node2D) -> void:
	if spinning_state != current_state:
		spinning_state.target_node = target_node
	transition_to(spinning_state)


func transition_to_exploding_state() -> void:
	transition_to(exploding_state)


func _enter_state(state: SpinnerState) -> void:
	current_state = state
	state.on_enter()


func _exit_state(state: SpinnerState) -> void:
	state.on_exit()

### END GENERATED CONTENT ###
