### spinner_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SpinnerStateIdle
extends SpinnerState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###


func on_enter() -> void:
	spinner.hit_box.area_entered.connect(on_hit)
	spinner.hit_box_collider.set_deferred("disabled", false)
	spinner.player_detection.area_entered.connect(on_detected)
	spinner.detection_collider.set_deferred("disabled", false)


func on_exit() -> void:
	spinner.hit_box.area_entered.disconnect(on_hit)
	spinner.hit_box_collider.set_deferred("disabled", true)
	spinner.player_detection.area_entered.disconnect(on_detected)
	spinner.detection_collider.set_deferred("disabled", true)


func on_detected(area: Area2D) -> void:
	spinner.player_sighted_sfx.play()
	fsm.transition_to_spinning_state(area)
