### spinner_state_spinning.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SpinnerStateSpinning
extends SpinnerState

var target_node: Node2D

func _to_string() -> String:
	return "spinning"

### END GENERATED CONTENT ###

var is_spinning: bool
var target_position: Vector2

func on_enter() -> void:
	var trans_id: int = fsm.transition_id
	is_spinning = false
	spinner.hit_box.area_entered.connect(on_hit)
	spinner.hit_box_collider.set_deferred("disabled", false)
	spinner.sprite.play("speed_up")
	await spinner.sprite.animation_finished
	if trans_id != fsm.transition_id:
		return
	spinner.sprite.play("spin")
	await Util.timer(Spinner.TARGETING_DELAY)
	if trans_id != fsm.transition_id:
		return
	spinner.roll_whoosh_sfx.play()
	target_position = target_node.global_position
	spinner.target_sprite.global_position = target_position
	spinner.target_sprite.show()
	spinner.target_sprite.play("target")
	is_spinning = true


func on_exit() -> void:
	is_spinning = false
	spinner.hit_box.area_entered.disconnect(on_hit)
	spinner.hit_box_collider.set_deferred("disabled", true)


func on_physics_process(delta: float) -> void:
	if is_spinning:
		spinner.global_position = spinner.global_position.move_toward(target_position, Spinner.SPIN_SPEED * delta)

		if spinner.global_position.is_equal_approx(target_position):
			fsm.transition_to_exploding_state()
