### spinner_state.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

@abstract
class_name SpinnerState
extends RefCounted

var spinner: Spinner
var fsm: SpinnerFSM:
	get: return _fsm_ref.get_ref() as SpinnerFSM

var _fsm_ref: WeakRef


func _init(spinner_: Spinner, fsm_: SpinnerFSM) -> void:
	spinner = spinner_
	_fsm_ref = weakref(fsm_)

@warning_ignore_start("unused_parameter")
func on_enter() -> void: pass
func on_exit() -> void: pass
func on_input(event: InputEvent) -> void: pass
func on_process(delta: float) -> void: pass
func on_physics_process(delta: float) -> void: pass
@warning_ignore_restore("unused_parameter")

### END GENERATED CONTENT ###

func on_hit(_area: Area2D) -> void:
	fsm.transition_to_exploding_state()
