### spinner_state_exploding.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name SpinnerStateExploding
extends SpinnerState

func _to_string() -> String:
	return "exploding"

### END GENERATED CONTENT ###

func on_enter() -> void:
	spinner.sprite.play("explode")
	spinner.explode_sfx.play()
	if spinner.target_sprite.visible:
		spinner.target_sprite.play_backwards("target")
		await spinner.target_sprite.animation_finished
		spinner.target_sprite.hide()
	await spinner.sprite.animation_finished
	spinner.sprite.hide()
