### blaster_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name BlasterStateIdle
extends BlasterState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###

const FIRE_DELAY: float = 1

var _fire_delay_remaining: float
var _initial_delay_applied: bool


func on_enter() -> void:
	blaster.sprite.play("idle")

	if not _initial_delay_applied:
		_initial_delay_applied = true
		_fire_delay_remaining = blaster.delay


func on_process(delta: float) -> void:
	if blaster.auto:
		_fire_delay_remaining -= delta
		if _fire_delay_remaining < 0:
			_fire_delay_remaining = FIRE_DELAY
			if blaster.on_screen_notifier.is_on_screen():
				fsm.transition_to_firing_state()
				return
