### blaster_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name BlasterStateIdle
extends BlasterState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###

func on_enter() -> void:
	blaster.sprite.play("idle")
