### blaster_fsm.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name BlasterFSM
extends RefCounted

signal transitioned(from_state: BlasterState, to_state: BlasterState)

var idle_state: BlasterStateIdle
var firing_state: BlasterStateFiring

var current_state: BlasterState
var transition_id: int = 0


func _init(blaster_: Blaster) -> void:
	idle_state = BlasterStateIdle.new(blaster_, self)
	firing_state = BlasterStateFiring.new(blaster_, self)
	_enter_state(idle_state)


func _to_string() -> String:
	return "BlasterFSM{state=%s}" % str(current_state)


func input(event: InputEvent) -> void:
	current_state.on_input(event)


func process(delta: float) -> void:
	current_state.on_process(delta)


func physics_process(delta: float) -> void:
	current_state.on_physics_process(delta)


func transition_to(new_state: BlasterState) -> void:
	if new_state == current_state:
		return
	var previous_state: BlasterState = current_state
	_exit_state(current_state)
	transition_id += 1
	_enter_state(new_state)
	transitioned.emit(previous_state, new_state)


func transition_to_idle_state() -> void:
	transition_to(idle_state)


func transition_to_firing_state() -> void:
	transition_to(firing_state)


func _enter_state(state: BlasterState) -> void:
	current_state = state
	state.on_enter()


func _exit_state(state: BlasterState) -> void:
	state.on_exit()

### END GENERATED CONTENT ###
