### blaster_state_firing.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name BlasterStateFiring
extends BlasterState

func _to_string() -> String:
	return "firing"

### END GENERATED CONTENT ###

func on_enter() -> void:
	blaster.sprite.play("fire")
	blaster.sprite.frame_changed.connect(_on_frame_changed)
	await blaster.sprite.animation_finished
	blaster.sprite.frame_changed.disconnect(_on_frame_changed)
	fsm.transition_to_idle_state()
	

func _on_frame_changed() -> void:
	if blaster.sprite.frame == 4:
		Projectile.spawn(blaster.projectile_spawn.global_position, blaster._fire_direction)
		blaster.fire_sfx.play()
