### blaster_state_firing.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name BlasterStateFiring
extends BlasterState

func _to_string() -> String:
	return "firing"

### END GENERATED CONTENT ###

func on_enter() -> void:
	blaster.sprite.play("fire")
