### trapper_state_snapping.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name TrapperStateSnapping
extends TrapperState

func _to_string() -> String:
	return "snapping"

### END GENERATED CONTENT ###

func on_enter() -> void:
	trapper.sprite.play("activate")
	await trapper.sprite.animation_finished
	await Util.timer(Trapper.RESET_TIME)
	fsm.transition_to_idle_state()
