### trapper_fsm.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name TrapperFSM
extends RefCounted

signal transitioned(from_state: TrapperState, to_state: TrapperState)

var idle_state: TrapperStateIdle
var snapping_state: TrapperStateSnapping

var current_state: TrapperState
var transition_id: int = 0


func _init(trapper_: Trapper) -> void:
	idle_state = TrapperStateIdle.new(trapper_, self)
	snapping_state = TrapperStateSnapping.new(trapper_, self)
	_enter_state(idle_state)


func _to_string() -> String:
	return "TrapperFSM{state=%s}" % str(current_state)


func input(event: InputEvent) -> void:
	current_state.on_input(event)


func process(delta: float) -> void:
	current_state.on_process(delta)


func physics_process(delta: float) -> void:
	current_state.on_physics_process(delta)


func transition_to(new_state: TrapperState) -> void:
	if new_state == current_state:
		return
	var previous_state: TrapperState = current_state
	_exit_state(current_state)
	transition_id += 1
	_enter_state(new_state)
	transitioned.emit(previous_state, new_state)


func transition_to_idle_state() -> void:
	transition_to(idle_state)


func transition_to_snapping_state() -> void:
	transition_to(snapping_state)


func _enter_state(state: TrapperState) -> void:
	current_state = state
	state.on_enter()


func _exit_state(state: TrapperState) -> void:
	state.on_exit()

### END GENERATED CONTENT ###
