### trapper_state.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

@abstract
class_name TrapperState
extends RefCounted

var trapper: Trapper
var fsm: TrapperFSM:
	get: return _fsm_ref.get_ref() as TrapperFSM

var _fsm_ref: WeakRef


func _init(trapper_: Trapper, fsm_: TrapperFSM) -> void:
	trapper = trapper_
	_fsm_ref = weakref(fsm_)

@warning_ignore_start("unused_parameter")
func on_enter() -> void: pass
func on_exit() -> void: pass
func on_input(event: InputEvent) -> void: pass
func on_process(delta: float) -> void: pass
func on_physics_process(delta: float) -> void: pass
@warning_ignore_restore("unused_parameter")

### END GENERATED CONTENT ###
