### trapper_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name TrapperStateIdle
extends TrapperState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###

func on_enter() -> void:
	trapper.collider.set_deferred("disabled", false)
	trapper.collision_area.area_entered.connect(_on_collision)
	trapper.sprite.play("idle")


func on_exit() -> void:
	trapper.collider.set_deferred("disabled", true)
	trapper.collision_area.area_entered.disconnect(_on_collision)


func _on_collision(_area: Area2D) -> void:
	fsm.transition_to_snapping_state()
