### roller_state_rolling.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name RollerStateRolling
extends RollerState

func _to_string() -> String:
	return "rolling"

### END GENERATED CONTENT ###

var is_rolling: bool

func on_enter() -> void:
	is_rolling = false
	roller.hit_box.area_entered.connect(on_hit)

	roller.sprite.play("preroll")
	await roller.sprite.animation_finished
	roller.sprite.play("roll")
	is_rolling = true


func on_exit() -> void:
	is_rolling = false
	roller.hit_box.area_entered.disconnect(on_hit)


func on_physics_process(delta: float) -> void:
	roller.velocity += roller.get_gravity() * delta
	if is_rolling:
		roller.velocity.x = move_toward(roller.velocity.x, roller.direction * Roller.ROLL_SPEED, Roller.ROLL_ACCEL * delta)
	roller.move_and_slide()
