### roller_state.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

@abstract
class_name RollerState
extends RefCounted

var roller: Roller
var fsm: RollerFSM:
	get: return _fsm_ref.get_ref() as RollerFSM

var _fsm_ref: WeakRef


func _init(roller_: Roller, fsm_: RollerFSM) -> void:
	roller = roller_
	_fsm_ref = weakref(fsm_)

@warning_ignore_start("unused_parameter")
func on_enter() -> void: pass
func on_exit() -> void: pass
func on_input(event: InputEvent) -> void: pass
func on_process(delta: float) -> void: pass
func on_physics_process(delta: float) -> void: pass
@warning_ignore_restore("unused_parameter")

### END GENERATED CONTENT ###

func on_hit(area: Area2D) -> void:
	var player_hit_box: PlayerHitBox = area as PlayerHitBox
	if player_hit_box:
		player_hit_box.hit(Roller.DAMAGE_AMOUNT, roller.global_position, Roller.KNOCKBACK_AMOUNT)

	fsm.transition_to_exploding_state()
