### roller_state_exploding.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name RollerStateExploding
extends RollerState

func _to_string() -> String:
	return "exploding"

### END GENERATED CONTENT ###

func on_enter() -> void:
	roller.sprite.play("explode")
	await roller.sprite.animation_finished
