### roller_state_rolling.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name RollerStateRolling
extends RollerState

func _to_string() -> String:
	return "rolling"

### END GENERATED CONTENT ###

const FALLEN_THRESHOLD: float = 216

var is_rolling: bool
var was_on_floor: bool
var distance_fallen: float


func on_enter() -> void:
	is_rolling = false
	was_on_floor = true
	distance_fallen = 0
	roller.hit_box.area_entered.connect(on_hit)

	roller.sprite.play("preroll")
	await roller.sprite.animation_finished
	roller.sprite.play("roll")
	roller.roll_sfx.play()
	roller.roll_whoosh_sfx.play()
	is_rolling = true


func on_exit() -> void:
	is_rolling = false
	roller.hit_box.area_entered.disconnect(on_hit)


func on_physics_process(delta: float) -> void:
	roller.velocity += roller.get_gravity() * delta
	distance_fallen += roller.velocity.y * delta

	var fall_threshold_met: bool = roller.is_on_floor() \
		and not was_on_floor \
		and distance_fallen > FALLEN_THRESHOLD
	if fall_threshold_met or roller.is_on_wall():
		fsm.transition_to_exploding_state()
		return

	was_on_floor = roller.is_on_floor()

	if is_rolling:
		var frame: int = roller.sprite.frame
		var frame_progress: float = roller.sprite.frame_progress
		if roller.is_on_floor():
			roller.sprite.animation = "roll"
		else:
			roller.sprite.animation = "air_roll"
		roller.sprite.set_frame_and_progress(frame, frame_progress)

		roller.velocity.x = move_toward(roller.velocity.x, roller.direction * Roller.ROLL_SPEED, Roller.ROLL_ACCEL * delta)

	roller.move_and_slide()
