### roller_state_idle.gd ###
### Auto-generated by godot-gen-tool — do not edit this generated section by hand. ###
### BEGIN GENERATED CONTENT ###

class_name RollerStateIdle
extends RollerState

func _to_string() -> String:
	return "idle"

### END GENERATED CONTENT ###

func on_enter() -> void:
	roller.sprite.play("idle")
	roller.player_ray_cast.enabled = true
	roller.hit_box.area_entered.connect(on_hit)


func on_exit() -> void:
	roller.player_ray_cast.enabled = false
	roller.hit_box.area_entered.disconnect(on_hit)


func on_physics_process(delta: float) -> void:
	roller.velocity += roller.get_gravity() * delta
	roller.move_and_slide()

	if roller.player_ray_cast.is_colliding():
		fsm.transition_to_rolling_state()
		return
