name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      
concurrency: preview-${{ github.ref }}

env:
  EXPORT_DIR: build/web

jobs:
  build:
    uses:
      ./.github/workflows/build.yml

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with: 
          name: web-export
          path: ${{ env.EXPORT_DIR }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ${{ env.EXPORT_DIR }}
          preview-branch: gh-pages
          qr-code: true
